### ISSUE TITLE
commuter installation on AWS 

### ISSUE THREAD

**Issue by KailasJanardhanan** [nteract/commuter#251]
**Application or Package Used**
Tried to install commuter using the command npm install @nteract/commuter -g
I tried it on Ubuntu instance(VM) on AWS.

**Describe the bug**
I am getting the following error
Error: Cannot find module '../../babel.flow.config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/lib/node_modules/@nteract/commuter/node_modules/@nteract/webpack-configurator/index.js:12:25)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)

**To Reproduce**
1. Take an Ubuntu 18.04.1 instance on AWS
2. Install npm by the following commands
    curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
    sudo apt install nodejs
3. Install commuter using the command - npm install @nteract/commuter -g
4. Post this if we just run the command  'commuter', you will get the exception mentioned above

**Expected behavior**
Proper installation.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.1 instance on AWS
 - Browser NA
 - Version NA

**Additional context**
NA

**Comment by asyd** [comment]
Same issue here, any news about it?

**Comment by GagandeepS** [comment]
Any workaround of this? I am facing the same issue.

**Comment by mstewart141** [comment]
@jdetle i am curious if you have any update on this issue, or if you can recommend someone i might ping RE the above? thank you!!
