### ISSUE TITLE
Default value for COMMUTER_S3_ENDPOINT shouldn't be an empty string	

### ISSUE THREAD

**Issue by elvinx** [nteract/commuter#298]
I am trying to use commuter with s3 and if I don't set COMMUTER_S3_ENDPOINT the default is

``` var s3Endpoint = env.COMMUTER_S3_ENDPOINT || "" ```

this causes 
```
rror: connect ECONNREFUSED 127.0.0.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14) {
  message: 'connect ECONNREFUSED 127.0.0.1:443',
  errno: -61,
  code: 'NetworkingError',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 443,
  region: 'us-east-1',
  hostname: '',
  retryable: true,
  time: 2020-06-23T10:28:51.483Z
} Error: connect ECONNREFUSED 127.0.0.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14)
```

However it works fine if it is set to null.

**Comment by captainsafia** [comment]
Thanks for reporting this issue, @elvinx!

Would you like to submit a pull request with a fix for this?

**Comment by rgbkrk** [comment]
Hi! This project was abandoned for a while, but we're back and cleaning house.

We're closing older issues as part of this maintenance, but we haven't forgotten about you! If this is still relevant to you, please open a new issue with updated context and we'll take a look. We're happy to review PRs if you'd like to contribute a fix.
