### ISSUE TITLE
Docker image fails to build. Project abandoned?

### ISSUE THREAD

**Issue by etrippler** [nteract/commuter#348]
Noticed that the Dockerfile fails to build today. Is this project still active?

Stack trace on the build failure below:

```
❯ docker build .
[+] Building 24.1s (20/26)                                                                        docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                              0.0s
 => => transferring dockerfile: 1.74kB                                                                            0.0s
 => [internal] load .dockerignore                                                                                 0.0s
 => => transferring context: 116B                                                                                 0.0s
 => [internal] load metadata for docker.io/library/node:14-slim                                                   1.5s
 => [internal] load metadata for docker.io/library/node:14                                                        1.5s
 => [internal] load build context                                                                                 0.0s
 => => transferring context: 584.35kB                                                                             0.0s
 => https://github.com/krallin/tini/releases/download/v0.19.0/tini                                                0.7s
 => [release 1/9] FROM docker.io/library/node:14-slim@sha256:198142146b4c47193348f6415da769bdb5035c16fcab051c38c  0.0s
 => [dependencies 1/6] FROM docker.io/library/node:14@sha256:a158d3b9b4e3fa813fa6c8c590b8f0a860e015ad4e59bbce574  0.0s
 => CACHED [dependencies 2/6] RUN DEBIAN_FRONTEND=noninteractive   apt-get update &&   apt-get install --yes --n  0.0s
 => CACHED [dependencies 3/6] RUN mkdir -p /opt/build                                                             0.0s
 => CACHED [dependencies 4/6] WORKDIR /opt/build                                                                  0.0s
 => CACHED [build 2/6] RUN mkdir -p /opt/build                                                                    0.0s
 => CACHED [build 3/6] WORKDIR /opt/build                                                                         0.0s
 => CACHED [build 4/6] COPY ./src ./src                                                                           0.0s
 => CACHED [build 5/6] COPY [   babel.config.js,   next.config.js,   package.json,   yarn.lock,   ./ ]            0.0s
 => ERROR [build 6/6] RUN yarn install &&   yarn build                                                           22.6s
 => CACHED [release 2/9] ADD https://github.com/krallin/tini/releases/download/v0.19.0/tini /tini                 0.0s
 => CACHED [release 3/9] RUN chmod +x /tini                                                                       0.0s
 => CACHED [release 4/9] RUN mkdir -p /opt/app                                                                    0.0s
 => CACHED [release 5/9] WORKDIR /opt/app                                                                         0.0s
------
 > [build 6/6] RUN yarn install &&   yarn build:
0.209 yarn install v1.22.19
0.271 [1/4] Resolving packages...
0.477 [2/4] Fetching packages...
16.54 [3/4] Linking dependencies...
16.54 warning " > @nteract/directory-listing@2.1.0" has unmet peer dependency "styled-components@>= 4".
16.54 warning " > @nteract/presentational-components@3.3.13" has unmet peer dependency "styled-components@>= 4".
16.54 warning " > @nteract/notebook-preview@11.0.4-alpha.0" has unmet peer dependency "immutable@^4.0.0-rc.12".
20.41 [4/4] Building fresh packages...
21.99 error /opt/build/node_modules/canvas: Command failed.
21.99 Exit code: 1
21.99 Command: node-pre-gyp install --fallback-to-build
21.99 Arguments:
21.99 Directory: /opt/build/node_modules/canvas
21.99 Output:
21.99 node-pre-gyp info it worked if it ends with ok
21.99 node-pre-gyp info using node-pre-gyp@0.15.0
21.99 node-pre-gyp info using node@14.21.3 | linux | arm64
21.99 node-pre-gyp WARN Using request for node-pre-gyp https download
21.99 node-pre-gyp info check checked for "/opt/build/node_modules/canvas/build/Release/canvas.node" (not found)
21.99 node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.7.0/canvas-v2.7.0-node-v83-linux-glibc-arm64.tar.gz
21.99 node-pre-gyp http 404 https://github.com/Automattic/node-canvas/releases/download/v2.7.0/canvas-v2.7.0-node-v83-linux-glibc-arm64.tar.gz
21.99 node-pre-gyp WARN Tried to download(404): https://github.com/Automattic/node-canvas/releases/download/v2.7.0/canvas-v2.7.0-node-v83-linux-glibc-arm64.tar.gz
21.99 node-pre-gyp WARN Pre-built binaries not found for canvas@2.7.0 and node@14.21.3 (node-v83 ABI, glibc) (falling back to source compile with node-gyp)
21.99 node-pre-gyp http 404 status code downloading tarball https://github.com/Automattic/node-canvas/releases/download/v2.7.0/canvas-v2.7.0-node-v83-linux-glibc-arm64.tar.gz
21.99 gyp info it worked if it ends with ok
21.99 gyp info using node-gyp@5.1.1
21.99 gyp info using node@14.21.3 | linux | arm64
21.99 gyp info ok
21.99 gyp info it worked if it ends with ok
21.99 gyp info using node-gyp@5.1.1
21.99 gyp info using node@14.21.3 | linux | arm64
21.99 gyp info find Python using Python version 2.7.16 found at "/usr/bin/python"
21.99 gyp http GET https://nodejs.org/download/release/v14.21.3/node-v14.21.3-headers.tar.gz
21.99 gyp http 200 https://nodejs.org/download/release/v14.21.3/node-v14.21.3-headers.tar.gz
21.99 gyp http GET https://nodejs.org/download/release/v14.21.3/SHASUMS256.txt
21.99 gyp http 200 https://nodejs.org/download/release/v14.21.3/SHASUMS256.txt
21.99 gyp info spawn /usr/bin/python
21.99 gyp info spawn args [
21.99 gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
21.99 gyp info spawn args   'binding.gyp',
21.99 gyp info spawn args   '-f',
21.99 gyp info spawn args   'make',
21.99 gyp info spawn args   '-I',
21.99 gyp info spawn args   '/opt/build/node_modules/canvas/build/config.gypi',
21.99 gyp info spawn args   '-I',
21.99 gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
21.99 gyp info spawn args   '-I',
21.99 gyp info spawn args   '/root/.cache/node-gyp/14.21.3/include/node/common.gypi',
21.99 gyp info spawn args   '-Dlibrary=shared_library',
21.99 gyp info spawn args   '-Dvisibility=default',
21.99 gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/14.21.3',
21.99 gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
21.99 gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/14.21.3/<(target_arch)/node.lib',
21.99 gyp info spawn args   '-Dmodule_root_dir=/opt/build/node_modules/canvas',
21.99 gyp info spawn args   '-Dnode_engine=v8',
21.99 gyp info spawn args   '--depth=.',
21.99 gyp info spawn args   '--no-parallel',
21.99 gyp info spawn args   '--generator-output',
21.99 gyp info spawn args   'build',
21.99 gyp info spawn args   '-Goutput_dir=.'
21.99 gyp info spawn args ]
21.99 Package pangocairo was not found in the pkg-config search path.
21.99 Perhaps you should add the directory containing `pangocairo.pc'
21.99 to the PKG_CONFIG_PATH environment variable
21.99 No package 'pangocairo' found
21.99 gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
21.99 gyp ERR! configure error
21.99 gyp ERR! stack Error: `gyp` failed with exit code: 1
21.99 gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
21.99 gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
21.99 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
21.99 gyp ERR! System Linux 6.4.16-linuxkit
21.99 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/opt/build/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/opt/build/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
21.99 gyp ERR! cwd /opt/build/node_modules/canvas
21.99 gyp ERR! node -v v14.21.3
21.99 gyp ERR! node-gyp -v v5.1.1
21.99 gyp ERR! not ok
21.99 node-pre-gyp ERR! build error
21.99 node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/build/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/opt/build/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
21.99 node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/build/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
21.99 node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
21.99 node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1088:16)
21.99 node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
21.99 node-pre-gyp ERR! System Linux 6.4.16-linuxkit
21.99 node-pre-gyp ERR! command "/usr/local/bin/node" "/opt/build/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
21.99 node-pre-gyp ERR! cwd /opt/build/node_modules/canvas
21.99 node-pre-gyp ERR! node -v v14.21.3
21.99 node-pre-gyp ERR! node-pre-gyp -v v0.15.0
21.99 node-pre-gyp ERR! not ok
21.99 Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/build/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/opt/build/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
21.99 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
Dockerfile:19
--------------------
  18 |
  19 | >>> RUN yarn install && \
  20 | >>>   yarn build
  21 |
--------------------
ERROR: failed to solve: process "/bin/sh -c yarn install &&   yarn build" did not complete successfully: exit code: 1
```

**Comment by rgbkrk** [comment]
Honestly? It was abandoned. However - we're back and happy to review PRs! I don't intend to use this personally, but if the community wants to push it forward, let's do it. Send PRs our way.
